spring:
    sql:
        init:
            encoding: utf-8
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:postgresql://127.0.0.1:5433/board
        password: 1234
        username: postgres
        hikari:
            connection-timeout: 3000
            validation-timeout: 3000
            minimum-idle: 5
            max-lifetime: 240000
            maximum-pool-size: 20
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
                use_sql_comments: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

